<?php

	require_once 'defines.php';
	require_once 'parameter.class.php';

	$GLOBALS['MAMP_INST_PARAMETERS'] = array(
		
		'MAMP_EXTRA_DB_HOST' => new parameter('MAMP_EXTRA_DB_HOST', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_DB_NAME' => new parameter('MAMP_EXTRA_DB_NAME', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_DB_PORT' => new parameter('MAMP_EXTRA_DB_PORT', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_DB_USERNAME' => new parameter('MAMP_EXTRA_DB_USERNAME', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_DB_PASSWORD' => new parameter('MAMP_EXTRA_DB_PASSWORD', PARAM_TYPE_PASSWORD),
		'MAMP_EXTRA_DB_CHARSET' => new parameter('MAMP_EXTRA_DB_CHARSET', PARAM_TYPE_TEXT),

		'MAMP_EXTRA_SITE_ADDRESS' => new parameter('MAMP_EXTRA_SITE_ADDRESS', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_SITE_NAME' => new parameter('MAMP_EXTRA_SITE_NAME', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_SITE_PATH' => new parameter('MAMP_EXTRA_SITE_PATH', PARAM_TYPE_FILE_PATH),
		
		'MAMP_EXTRA_ADMIN_EMAIL' => new parameter('MAMP_EXTRA_ADMIN_EMAIL', PARAM_TYPE_EMAIL),
		
		'MAMP_EXTRA_ACCOUNT_USERNAME' => new parameter('MAMP_EXTRA_ACCOUNT_USERNAME', PARAM_TYPE_TEXT),
		'MAMP_EXTRA_ACCOUNT_PASSWORD' => new parameter('MAMP_EXTRA_ACCOUNT_PASSWORD', PARAM_TYPE_PASSWORD),
		'MAMP_EXTRA_SITE_START_PAGE' => new parameter('MAMP_EXTRA_SITE_START_PAGE', PARAM_TYPE_TEXT)		
	)


?>